### PR TITLE
iPhone X support & React Native upgrade

### PR DESCRIPTION
**Pull request by Photonios**
First of all, many many thanks for this app. I've been using it intensively on every iPhone I've owned and I always come back to this app. It's one of the first things I install. I got my iPhone X a while ago and hoped someone else would update this app for the iPhone X. Nobody did, so I took it upon myself :) 

Addresses issue #14 

* Upgrade React Native to be able to build with latest XCode, required to build for iPhone X. Some packages and components have been deprecated and had to be upgraded.

* I really do not enjoy the hacks put in place for the iPhone X. I had to hard-code the offset from the top because the navbar is taller on iPhone X. This can be more elegantly solved by using `react-navigation`, which takes care of that automatically. However, that would be quite an intensive change.

* I've created more padding at the bottom so that the bumper bar is not overlapping any content.

I understand the iPhone X specific changes are really a hack and I'd really like to implement a more elegant solution. Such solutions would require more dramatic changes, which I do not really feel comfortable doing right now.

simulator screen shot - iphone x - 2018-06-25 at 11 24 07
simulator screen shot - iphone x - 2018-06-25 at 11 24 39
simulator screen shot - iphone x - 2018-06-25 at 11 25 05

### CODE REVIEW

**Comment by russelldavis** [comment]
Any reason not to merge this?

**Comment by cheeaun** [comment]
@russelldavis hey! very sorry for this super late reply.

Few reasons:
- I've been seriously getting out-of-loop from any latest changes in the React Native world.
- Been rather busy with my other projects (blame myself for not being able to focus on one thing for a long period of time).
- Also been getting sick a lot for the past few months 😅
- I don't have/use iPhone X so that kinda deters me from updating this a little (I'm still using the current HackerWeb version on my iPhone 8 😄 )

However(!), I actually did try upgrading this even before this PR, pretty much did almost everything you did in this PR, except I kind of dislike the (temporary?) hacks. At one point, I thought of giving up the old navigator and use `react-navigation` but that's a huge change itself. As always, changes in non-RN files like `LaunchScreen.xib` and `HackerWeb.xcscheme` always scares me because I have no idea what they do 😄😄 #rant 

Currently I'm in "waiting mode", observing if there's anything new or non-hacky fixes for this project. Personally I wouldn't merge yet but it would great if you could continuously update this (I suppose you're already running a custom-built version of HW on your iPhone?) because this is actually a good reference and strong reminder for me 😬

**Comment by russelldavis** [comment]
Thanks for the detailed reply! I'm actually not the author of this PR, just a happy long-time user who recently upgraded to the XS and wanted this to look better there. I'll keep watching here for updates.

**Comment by cheeaun** [comment]
@russelldavis lol, obviously I didn't read the author of PR properly before commenting 😳 😆 Thanks a lot to @Photonios then :D

**Comment by Photonios** [comment]
Hey, author here :)

Sorry it took so long to get back to this. I'll see if I can put in some effort to remove some of the hacks. They are not pretty. 

Thanks for looking at it 👍

**Review by ken662 — APPROVED** [review]

**Comment by cheeaun** [comment]
V2 now supports this, on a separate repo https://github.com/cheeaun/hackerweb-native-2

**Pull request closed without merging**
